config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }

  get 'home/index'
  get 'how_to_use' => 'home#how_to_use'

  root to: "home#index"

  resources :rooms, only: [:index, :show, :new, :create]
  resources :users, only: [:show]

  namespace :settings do
    get '/profile'  => 'profile#show'
    put '/profile'  => 'profile#update'
    get '/account'  => 'account#show'
    patch '/account'  => 'account#update'
  end

  mount API::Root => '/api'
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user, optional: true

  def self.providers
    ['twitter', 'google']
  end

  def provider_url
    if provider == 'twitter'
      "https://twitter.com/#{name}"
    else
      nil
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :video
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :queue, foreign_key: 'queue_id', class_name: 'VideoQueue'
  belongs_to :user
end

app/models/comment_reaction.rb
class CommentReaction < ApplicationRecord
  belongs_to :comment, foreign_key: 'comment_id', class_name: '::Comment'
  belongs_to :user
end

app/models/queue_reaction.rb
class QueueReaction < ApplicationRecord
  TYPE_LIKE = 1
  TYPE_DISLIKE = 2

  belongs_to :queue, foreign_key: 'queue_id', class_name: 'RoomQueue'
  belongs_to :user
end

app/models/reaction.rb
class Reaction < ApplicationRecord
  belongs_to :queue, foreign_key: 'queue_id', class_name: 'VideoQueue'
  belongs_to :user
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :organization
  has_many :participants, foreign_key: :room_id, class_name: 'RoomParticipant'
  has_many :queues, foreign_key: :room_id, class_name: 'RoomQueue'
  has_many :videos, through: :queues
  has_many :comments, through: :queues

  def playing_queue
    queues.find_by({state: RoomQueue::STATE_PLAYING})
  end

  def next_queue
    queues.where({ state: RoomQueue::STATE_QUEUED }).order(:created_at).first
  end

  def add_queue(user_id, video)
    queues << RoomQueue.create({
      user_id: user_id,
      video_id: video.id,
      state: RoomQueue::STATE_QUEUED,
    })
  end

  def latest_queue
    queues.where("state = #{::RoomQueue::STATE_FINISHED}").order('id DESC').limit(1).first
  end

  def current_queues
    queues.where("state IN (?)", [::RoomQueue::STATE_QUEUED, ::RoomQueue::STATE_PLAYING]).order(:id)
  end

  def current_participants
    participants.where('updated_at > ?', Time.now - 300)
  end
end

app/models/room_participant.rb
class RoomParticipant < ApplicationRecord
  belongs_to :room
  belongs_to :user

  def self.recently
    where('updated_at > ?', Time.now - 300)
  end
end

app/models/room_queue.rb
class RoomQueue < ApplicationRecord
  belongs_to :user
  belongs_to :video
  belongs_to :room

  has_many :comments, foreign_key: 'queue_id'
  has_many :reactions, foreign_key: 'queue_id', class_name: '::QueueReaction'

  STATE_QUEUED = 0
  STATE_PLAYING = 1
  STATE_FINISHED = 2
  STATE_STOPED = 3

  def play
    update({
      state: STATE_PLAYING,
      started_at: DateTime.now,
      finish_at: (DateTime.now.to_time + video.duration).to_datetime
    })
  end

  def can_finish?
    DateTime.now > finish_at
  end

  def finish
    update({state: STATE_FINISHED, finished_at: DateTime.now})
  end

  def stop
    if state == STATE_PLAYING
      finish
    else
      update({state: STATE_FINISHED})
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  has_many :accounts
  has_many :organization_users
  has_many :organizations, through: :organization_users

  has_many :queues, foreign_key: :user_id, class_name: 'RoomQueue'
  has_many :videos, through: :queues

  has_many :bookmarks, foreign_key: :user_id, class_name: 'Bookmark'
  has_many :bookmark_videos, through: :bookmarks, class_name: 'Video'

  has_many :reactions, foreign_key: 'user_id', class_name: '::QueueReaction'

  def email_required?
    false
  end

  def password_required?
    false
  end

  def nickname
    name ? name : email.split('@').first
  end

  def image_url
    accounts.length > 0 ?  accounts.first.image_url : "/assets/images/user.png"
  end

  def has_account?(provider)
    accounts.find_by(provider: provider)
  end

  def belong_organization?(organization)
    organizations.find_by({id: organization.id})
  end

  def generate_access_token
    ::Doorkeeper::AccessToken.create({
      application_id: nil,
      resource_owner_id: id,
      scopes: "public",
      expires_in: nil,
      use_refresh_token: false
    }) unless ::Doorkeeper::AccessToken.find_by({resource_owner_id: id})
  end

  def token
    ::Doorkeeper::AccessToken.find_by({resource_owner_id: id}).token
  end
end

app/models/video.rb
class Video < ApplicationRecord
  has_many :queues, class_name: 'RoomQueue', foreign_key: :video_id
  has_many :rooms, through: :queues

  has_many :bookmarks, class_name: 'Bookmark', foreign_key: :video_id

  PROVIDER_YOUTUBE = 1
end

app/models/video_queue.rb
class VideoQueue < ApplicationRecord
  belongs_to :user
  belongs_to :video
  belongs_to :room

  has_many :comments, foreign_key: 'queue_id'

  STATE_QUEUED = 0
  STATE_PLAYING = 1
  STATE_FINISHED = 2
  STATE_STOPED = 3

  def play
    update({
      state: STATE_PLAYING,
      started_at: DateTime.now,
      finish_at: (DateTime.now.to_time + video.duration).to_datetime
    })
  end

  def finish
    update({state: STATE_FINISHED, finished_at: DateTime.now})
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :access_token

  def access_token
    current_user.token
  end

  def after_sign_in_path_for(resource)
    rooms_path
  end
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
  before_action :authenticate_user

  def authenticate_user
    redirect_to new_user_session_path and return unless current_user
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def how_to_use
  end
end

app/controllers/rooms_controller.rb
class RoomsController < BaseController
  before_action :set_room, only: [:show]
  def index
    @rooms = Room.all
  end

  def show
  end

  def new
    @room = Room.new
  end

  def create
    room = Room.create(room_params)
    redirect_to room
  end

  private
  def set_room
    @room = Room.find_by({id: params[:id]})
  end

  def room_params
    params.require(:room).permit(:screen_name)
  end
end

app/controllers/settings/account_controller.rb
class Settings::AccountController < BaseController
  before_action :set_user, only: [:show, :update]

  def show
  end

  def update
    if @user.update(account_params)
      flash[:success] = "アカウント名を保存しました"
      redirect_to settings_account_path
    else
      if @user.find_by(name: params[:name])
        flash[:error] = "すでに利用されています"
      else
        flash[:error] = "すでに利用されています"
      end
      redirect_to settings_account_path
    end
  end

  private
  def set_user
    @user = User.find(current_user.id)
  end

  def account_params
    params.require(:user).permit(:name)
  end
end

app/controllers/settings/profile_controller.rb
class Settings::ProfileController < BaseController
  before_action :set_user, only: [:show]

  def show
  end

  def update
  end

  private
  def set_user
    @user = User.find(current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < BaseController
  before_action :set_user, only: [:show]

  def show
  end

  private
  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/how_to_use.html.slim
div#main.how-to-use
  nav.navbar.bg-secondary
    a.navbar-brand
      span
        img src="/assets/images/logo.png" height="18px"
        |   JukeHub
    button.navbar-toggler.hidden-md-up type="button" data-toggle="collapse" data-target="#collapse-bar" aria-expanded="true"
      i.fa.fa-bars
    div.container-fluid
      div#collapse-bar.collapse.navbar-toggleable-sm
        ul.nav.navbar-nav
          li.nav-item
            = link_to '使い方', how_to_use_path, class: 'nav-link'
  br
  div.container-fluid
    h1.display-5 JukeHubの使い方
    div.row
      div.col-sm-12
        h2.display-6.how-to-title ユーザ登録
        div.detail
          span 本サービスはユーザ登録を行ってからご利用ください。
          span ユーザ登録は
          span
            a href="/users/sign_up" こちら
          br
          br
      div.col-sm-12
        h2.display-6.how-to-title ログイン方法
        div.detail
          span 本サービスはログインが必須となります。ユーザ登録をされている方は
          a href="/users/sign_in" ログイン
          span をしてから本サービスをご利用ください
          br
          br
      div.col-sm-12
        h2.display-6.how-to-title 動画部屋での振る舞い方
        div.detail
          p 各グループには何部屋か設けられています。ログイン後は好きなグループの部屋に参加をしてください。
          p 音楽を聴くためにご利用される方はこれで準備は整いました。
          p 部屋では何人ものDJが自分が好きな音楽をYoutube動画で流しています。
      div.col-sm-12
        h2.display-6.how-to-title 動画部屋の使い方
        div.detail
          div.row
            div.col-sm-8
              img src="/assets/images/how_to_use_1.png" width="100%"
            div.col-sm-4
              p.step A Youtube動画の再生エリアです。部屋で流れているyoutubeの動画や音楽が再生されます。視聴者の方は音楽の音の調整などはyoutubeコントローラから行ってください。
              p.step B 現在流れている動画や音楽の情報や追加したDJの名前が表示されています。聞いていた音楽が気に入ったら「いいね」をしてあげるとDJが喜びます。一段上のエリアには現在部屋に参加している視聴者が表示されています。視聴者の趣味嗜好にあった音楽を流してあげられれば立派なDJの仲間入りです。
              p.step C 部屋の音楽のセットリストです。現在流れている音楽は緑色。次の曲からその下に表示されていきます。
              p.step D Youtubeの音楽の検索フォームです。このフォームから音楽を検索するとYoutubeの音楽の検索結果が表示されます。検索結果から音楽を追加するボタンをおすと、部屋のセットリストに音楽が追加されます。これであなたもDJの仲間入りです。
              p.step E YoutubeのURL入力用フォームです。Youtubeの動画を直接セットリストに追加したい場合は、YoutubeのURLをフォームに入力すれば、セットリストに追加されます。検索フォームと入力フォームどちらからでも音楽を追加することができますので、お好きな方をご利用ください。
              p.step F 各メニューがあります。自分のDJ名の設定やSNSアカウントの設定などを行うことができます。

app/views/home/index.html.slim
div#main
  nav.navbar.bg-secondary
    a.navbar-brand
      span
        img src="/assets/images/logo.png" height="18px"
        |   JukeHub
    button.navbar-toggler.hidden-md-up type="button" data-toggle="collapse" data-target="#collapse-bar" aria-expanded="true"
      i.fa.fa-bars
    div.container-fluid
      div#collapse-bar.collapse.navbar-toggleable-sm
        ul.nav.navbar-nav
          li.nav-item
            = link_to '使い方', how_to_use_path, class: 'nav-link'
        ul.nav.navbar-nav.nav-flex-icons
          li.nav-item
            = link_to 'ユーザ登録', new_user_registration_path, class: 'btn btn-sm btn-primary'
          li.nav-item
            = link_to 'ログイン', new_user_session_path, class: 'btn btn-sm btn-success'
  div.contents
    div.lp-description
      h1.display-4 JukeHub
      div.row
        div.col-lg-6
          p JukeHubはYoutube動画を使ったDJサービスです
        div.col-lg-6
  br
  br
  div.container-fluid
    div
      div.flex-center
        h2.display-5.main-title JukeHubとは
      div.flex-center
        p JukeHubはYoutubeの動画をDJのセットリストとして流すことができるサービスです
      div.flex-center
        p DJとして自分で音楽を流すことはもちろん、リスナーとして音楽を聴くこともできます
  br
  br
  div.flex-center
    h2.display-5 ご利用までの流れ
  div.container-fluid
    br
    div.row
      div.col-lg-3
        div.card.card-block.height250
          h4.card-title 1. ユーザ登録
          p.card-text
            | まずはユーザの登録を行いましょう。
            br
            = link_to 'ユーザ登録はこちらから', new_user_registration_path
      div.col-lg-3
        div.card.card-block.height250
          h4.card-title 2. グループへの参加
          p.card-text
            | DJグループに参加しましょう。
            br
            | まずはパブリックDJグループへの参加をおすすめします。
      div.col-lg-3
        div.card.card-block.height250
          h4.card-title 3. 部屋への参加
          p.card-text
            | DJグループには複数の部屋が用意されています。
            br
            | 流れている音楽をみて好みの部屋に参加しましょう。
      div.col-lg-3
        div.card.card-block.height250
          h4.card-title 4. 準備は整いました
          p.card-text Have a good Jukehub time !!!

app/views/rooms/_bookmark_search.html.slim
div#bookmarks.modal.fade tabindex="-1" role="dialog" aria-labelledby="youtube_modal" aria-hidden="true"
  div.modal-dialog role="document"
    div.modal-content
      div.modal-header
        button.close type="button" data-dismiss="modal" aria-label="Close"
          span aria-hidden="true" &times;
        h4#modal_title.modal-title.t_black ブックマーク
      div.modal-body
        | <template v-for="bookmark in bookmarks">
        |   <div class='card card-block'>
        |     <div class='row'>
        |       <div class='col-xs-2'>
        |         <img v-bind:src='bookmark.image_url' height='100%' width='100%'>
        |       </div>
        |       <div class='col-xs-8'>
        |         <h5 class='card-title'>{{bookmark.title}}</h4>
        |       </div>
        |       <div class='col-xs-2'>
        |         <button id="{{bookmark.video_id}}" class="btn btn-floating btn-small blue" v-on:click="add_video_from_result">
        |           <i class="fa fa-plus-circle" id="{{bookmark.video_id}}"></i>
        |         </button>
        |       </div>
        |     </div>
        |   </div>
        | </template>

app/views/rooms/_error_modal.html.slim
div#error_modal.modal.fade tabindex="-1" role="dialog" aria-labelledby="error_modal" aria-hidden="true"
  div.modal-dialog role="document"
    div.modal-content
      div.modal-header
        button.close type="button" data-dismiss="modal" aria-label="Close"
          span aria-hidden="true" &times;
        h4#modal-title 指定の動画は利用できません

app/views/rooms/_youtube_search.html.slim
div#search_result.modal.fade tabindex="-1" role="dialog" aria-labelledby="youtube_modal" aria-hidden="true"
  div.modal-dialog role="document"
    div.modal-content
      div.modal-header
        button.close type="button" data-dismiss="modal" aria-label="Close"
          span aria-hidden="true" &times;
        h4#modal_title.modal-title.t_black
          span 検索ワード: 
          span#search_query_title.t_black
      div.modal-body
        | <template v-for="result in search_results">
        |   <div class='card card-block'>
        |     <div class='row'>
        |       <div class='col-xs-2'>
        |         <img v-bind:src='result.image_url' height='100%' width='100%'>
        |       </div>
        |       <div class='col-xs-8'>
        |         <h5 class='card-title'>{{result.title}}</h4>
        |       </div>
        |       <div class='col-xs-2'>
        |         <button id="{{result.video_id}}" class="btn btn-floating btn-small blue" v-on:click="add_video_from_result">
        |           <i class="fa fa-plus-circle" id="{{result.video_id}}"></i>
        |         </button>
        |       </div>
        |     </div>
        |   </div>
        | </template>

app/views/rooms/index.html.slim
div
  = render partial: "/layouts/navbar"
  div.contents.container-fluid
    div.row
      div.col-md-9
        h1 部屋一覧
      div.col-md-3
        div.text-xs-right
          a href="/rooms/new"
            button.btn.btn-white type="button" 新規作成
    table.table.table-bordered
      thead
        th 部屋名
        th 参加者数
        th 現在流れている音楽
      tbody
        - @rooms.each do |room|
          tr
            td = link_to room.screen_name, room
            td.text-xs-right = "#{room.current_participants.length}人"
            - if room.playing_queue
              td = room.playing_queue.video.title
            - else
              td 現在音楽は流れておりません

app/views/rooms/new.html.slim
div
  = render partial: "/layouts/navbar"
  div.contents.container
    div.form-header.text-md-center
      h3.display-4
        i.fa.fa-pencil-square-o
        |  部屋作成
      hr.mt-2.md-2
    = form_for @room do |f|
      div.md-form
        i.fa.fa-address-card-o.prefix
        = f.text_field :screen_name, autocomplete: "off", placeholder: 'ルーム名', class: 'form-control'
      div.actions
        = f.submit "作成", class: 'btn btn-darkgray'
      hr.mt-2.md-2
      div.text-xs-right

app/views/rooms/show.html.slim
div#main.show
  = render partial: "/rooms/youtube_search"
  = render partial: "/rooms/bookmark_search"
  = render partial: "/rooms/error_modal"
  nav.navbar.navbar-dark.bg-darkgray
    span.bb
    a.navbar-brand = @room.screen_name
    button.navbar-toggler.hidden-md-up type="button" data-toggle="collapse" data-target="#collapse-bar" aria-expanded="true"
      i.fa.fa-bars
    div.container-fluid
      div#collapse-bar.collapse.navbar-toggleable-sm
        ul.nav.navbar-nav
        div.form-inline.pull-md-left
          input#search_query.form-control v-on:keydown.enter="aho" type="text" size='50%' placeholder=" Youtube検索"
          button#search_from_bookmark.btn.btn-darkgray v-on:click="search_from_bookmark" ブックマークから追加
        div.profileIcon
          ul.nav.navbar-nav.nav-flex-icons
            li.nav-item.avatar.dropdown.active
              a.nav-link.dropdown-toggle.waves-effect.waves-light type="button" id="dropdown_menu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"
                img.img-circle src="#{current_user.image_url}" height='24px'
              div.dropdown-menu.dropdown-right.dropdown-warning aria-labelledby="dropdown_menu" data-dropdown-in="fadeIn" data-dropdown-out="fadeOut"
                = link_to 'マイページ', "/users/#{current_user.id}", class: 'dropdown-item'
                div.dropdown-divider
                = link_to 'JukeHubの使い方', "/how_to_use", class: 'dropdown-item', target: '_blank'
                = link_to '部屋から出る', "/rooms", class: 'dropdown-item'


  div.container-fluid
    br
    div.row
      div.col-md-8
        iframe#player width="100%" height="400px" src="https://www.youtube.com/embed/ZWdMi2Cfp70" frameborder="0" allowfullscreen
        div#participants.card.card-block.nopad
          | <template v-for="participant in participants">
          |   <img class="horizontal" v-bind:src='participant.image_url' height="30px" width="30px" data-toggle="tooltip" data-placement="top" title="{{participant.name}}">
          | </template>
        div.card
          div.card-block
            div.row
              div.col-lg-12
                h4#now_playing_title.card-title
                div.video-action
                  button.btn.btn-floating.btn-small.btn-darkgray v-on:click="like"
                    i.fa.fa-thumbs-up
                  button.btn.btn-floating.btn-small.btn-darkgray v-on:click="add_bookmark"
                    i.fa.fa-bookmark
            img#user_image src="/assets/images/user.png" height="48" width="48"
            a#now_playing_user
            div.like-info.text-xs-right
              span#like_count 0
              span
                |  
              span いいね
      div.col-md-4
        div.card.card-block
          h5.urlTitle URLから直接追加
          div.md-form
            input#url.form-control v-on:keydown.enter="add" value="#{@q}" type='text' placeholder="https://www.youtube.com/watch?v=ZWdMi2Cfp70"
        div.scroller
          | <template v-for="queue in queues">
          |   <div class='card' v-if="queue.state == 0">
          |     <div class='card-block'>
          |       <div class='row'>
          |         <div class='col-xs-2'>
          |           <img v-bind:src='queue.image_url' height='100%' width='100%'>
          |         </div>
          |         <div class='col-xs-10'>
          |           <div class='row'>
          |             <div class='col-xs-11'>
          |               <h5 class='card-title'>{{queue.title}}</h5>
          |             </div>
          |             <div class='col-xs-1'>
          |               <a id="{{queue.id}}" class="activator" v-on:click="stop"><i id="{{queue.id}}" class="fa fa-ban"></i></a>
          |             </div>
          |           <p class='pull-xs-right'>{{queue.user.name}} / {{queue.duration_text}}</p>
          |           </div>
          |         </div>
          |       </div>
          |     </div>
          |   </div>
          |   <div class='card card-block card-success white-text' v-if="queue.state == 1">
          |     <div class='row'>
          |       <div class='col-xs-2'>
          |         <img v-bind:src='queue.image_url' height='100%' width='100%'>
          |       </div>
          |       <div class='col-xs-10'>
          |         <div class="row">
          |           <div class='col-xs-11'>
          |             <h5 class='card-title'>{{queue.title}}</h5>
          |           </div>
          |           <div class='col-xs-1'>
          |             <a id="{{queue.id}}" class="activator" v-on:click="stop"><i id="{{queue.id}}" class="fa fa-ban"></i></a>
          |           </div>
          |           <p class='pull-xs-right'>{{queue.user.name}} / {{queue.duration_text}}</p>
          |         </div>
          |       </div>
          |     </div>
          |   </div>
          | </template>

javascript:
  var v = new Vue({
    el: '#main',
    data: {
      search_results: [],
      bookmarks: [],
      queues: [],
      participants: [],
      now_playing: 0,
    },
    methods: {
      add: function(event) {
        var self = this;
        var url = $('#url').val();
        $.ajax({
          type: 'POST',
          url: '/api/rooms/#{@room.id}/queues',
          data: { url: url },
          success: function() {
            $('#url').val('');
            self.fetch_videos();
          },
          error: function(res, a) {
            $('#error_modal').modal('show');
          },
        });
      },
      add_bookmark: function() {
        var self = this;
        $.ajax({
          type: 'POST',
          url: '/api/bookmarks',
          data: { video_id: self.now_playing, },
          success: function (data, status, request) {
          },
          error: function(res) {
            $('#error_modal').modal('show');
          }
        })
      },
      fetch_videos: function() {
        var self = this;
        $.ajax({
          type: 'GET',
          url: '/api/rooms/#{@room.id}/queues',
          success: function (data, status, request) {
            self.queues = [];
            for (var i = 0; i < data.length; i++) {
              self.queues.push(data[i]);
            }
          },
        }).error(function (data, status, request) {})
      },
      get_video: function(callback) {
        $.ajax({
          type: 'GET',
          url: '/api/rooms/#{@room.id}/queues/playing',
          success: function(res) {
            if (res) {
              var video_title = res.video.title.length > 40 ? res.video.title.slice(0, 40) + ' ...' : res.video.title;
              $('#now_playing_title').text(video_title);
              $('#now_playing_user').text('@' + res.user_name);
              if (res.user) {
                $('#now_playing_user').attr('href', '/users/' + res.user.id);
              } else {
                $('#now_playing_user').attr('href', '#');
              }
              $('#user_image').attr("src", res.image_url);
              callback({ id: res.video.provider_video_id, title: res.video.title, behind: res.behind, user_name: res.user_name, user: res.user });
            } else {
              callback(false);
            }
          },
        })
      },
      play: function(video) {
        var url = 'https://www.youtube.com/embed/' + video.id;
        $('#player').attr('src', url + '?autoplay=1&rel=0&showinfo=0&start=' + video.behind);
      },
      like: function() {
        var self = this;
        $.ajax({
          type: 'POST',
          url: '/api/rooms/#{@room.id}/reactions',
          data: { type: 'like' },
          success: function() {
            self.fetch_reactions();
          }
        });
      },
      fetch_reactions: function() {
        $.ajax({
          type: 'GET',
          url: '/api/rooms/#{@room.id}/reactions',
          success: function(res) {
            $('#like_count').text(res.like);
          }
        });
      },
      fetch_participants: function() {
        var self = this;
        $.ajax({
          type: 'GET',
          url: '/api/rooms/#{@room.id}/participants',
          success: function (data, status, request) {
            self.participants = [];
            for (var i = 0; i < data.length; i++) {
              self.participants.push(data[i]);
            }
          }
        });
      },
      stop: function(e, a, b) {
        var self = this;
        $.ajax({
          type: 'DELETE',
          url: '/api/rooms/#{@room.id}/queues/' + e.target.id,
          success: function(res) {
            self.fetch_videos();
          }
        });
      },
      watch: function() {
        var self = this;
        self.fetch_participants();
        this.fetch_reactions();
        this.get_video(function(video) {
          if (video && (self.now_playing != video.id)) {
            self.now_playing = video.id;
            self.play(video);
            var n = new Notification(video.title + "\n" + video.user_name);
            setTimeout(function() {
              n.close();
            }, 3 * 1000);
          }
          self.fetch_videos();
          setTimeout(function() {
            self.watch();
          }, 10 * 1000);
        });
      },
      aho: function() {
        var self = this;
        var query = $('#search_query').val();
        $.ajax({
          type: 'GET',
          url: '/api/search',
          data: { query: query },
          success: function (data, status, request) {
            self.search_results = [];
            for (var i = 0; i < data.result.length; i++) {
              self.search_results.push(data.result[i]);
            }
            $('#search_query_title').text(query);
            $('#search_result').modal();
          },
        });
      },
      add_video_from_result: function (event) {
        var self = this;
        var url = "https://www.youtube.com/watch?v=" + event.target.id;
        $.ajax({
          type: 'POST',
          url: '/api/rooms/#{@room.id}/queues',
          data: { url: url },
          success: function() {
            self.fetch_videos();
            $('#search_result').modal('hide');
          },
          error: function() {
            $('#error_modal').modal('show');
          },
        });
      },
      search_from_bookmark: function() {
        var self = this;
        $.ajax({
          type: 'GET',
          url: '/api/bookmarks',
          success: function(data, status, req) {
            self.bookmarks = [];
            for (var i = 0; i < data.result.length; i++) {
              console.log(data.result[i]);
              self.bookmarks.push(data.result[i]);
            }
            $('#bookmarks').modal();
          }
        });
      },
    }
  })
  v.watch();

app/views/settings/_menu.html.slim
div.list-group
  li.list-group-item メニュー
  a#menu_profile.list-group-item href="/settings/profile" プロフィール
  a#menu_account.list-group-item href="/settings/account" アカウント

app/views/settings/profile/show.html.slim
div
  = render partial: "/layouts/navbar"
  div.contents.container-fluid
    div.row
      div.col-lg-3
        = render partial: "/settings/menu"
      div.col-lg-9
        div.card
          h5.card-header プロフィール
          div.card-block
            p 現在プロフィール機能は実装中です。もうしばらくお待ち下さい。

javascript:
  $('#menu_profile').addClass('active');